---
title: "iGEM_BBa_J23100"
date: "2021-04-01"
output: 
  html_document:
  pdf_document:
    latex_engine: xelatex
mainfont : NanumGothic
---

# J23100
## Experience
``` {r, echo=FALSE}
id <- c(1)
team_name <- c("Sheffield")
year <- c(2016)
project <- c("create a device that could prevent the unnecessary use of antibiotics")
wiki <- c("http://2016.igem.org/Team:Sheffield")

igem_team <- data.frame(id, 
                        team_name, 
                        project, 
                        year, 
                        wiki)

```


``` {r, echo=FALSE}
library(data.table)

id <- 1:2
BBid <- c("BBa_J23100", "BBa_J23106")
type <- c(rep("Promoter",length(id)))
link <- c("-", "-")
backborn <- c(rep("pSB1C3",2))
team_name <- c(rep("Sheffield",2))
user <- rep("Lelp27", length(id))
device_id <- rep("BBa_K2016000", length(id))

igem_part <- data.table(id, BBid, type, backborn, link, device_id, team_name)
#igem_part
```

``` {r, echo=FALSE}
id <- 1:4
strain <- rep("W3110",4)
indc <- (rep("FeCl3",4))
conc <- c(0, 0, 100, 100)
value <- c(100000, 110000, 700000, 650000)
valunit <- rep("Fluorescence", length(id))
promoter <- c("BBa_J23106", "BBa_J23100", "BBa_J23106", "BBa_J23100")
incubhr <- c <- (rep("16-18h", length(id)))
incubtemp <- c(rep("37",length(id)))
  device_id <- rep("BBa_K2016000", length(id))
link <- c(rep("http://2016.igem.org/Team:Sheffield/project/science",4))

igem_obs <- data.table(id, strain, promoter, indc, conc, value, valunit, incubhr, incubtemp, device_id, link)

knitr::kable(igem_obs)
```
``` {r, echo=FALSE, include=FALSE}
library(tidyverse)
library(shiny)
library(DT)
```


``` {r, echo=FALSE}

igem_promoter <- igem_part %>%
  left_join(igem_team, by="team_name") %>%
  left_join(igem_obs, by="device_id")

knitr::kable(igem_promoter)
```

``` {r, echo=FALSE}
plot_data <- igem_promoter %>% 
  filter(BBid=="BBa_J23100") %>% 
  select(strain, conc, value) %>% 
  mutate(strain=factor(strain), conc=factor(conc))

ggplot(plot_data, aes(x=promoter, y=value, fill=conc)) +
  geom_bar(stat="identity", position=position_dodge(width=0.5), width=0.4) +
  scale_fill_manual(values=c("#ce1212", "#4a47a3")) +
  theme_bw()
```




